# Site settings
title: Octavio Leon
description: Contacto directo con Octavio_Leon
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Octavio Leon
user_description: Soy una persona de 20 años apasionada por el crecimiento personal y profesional. Resido en Cancún, Actualmente me encuentro estudiando una ingeniería en Sistemas Computacionales, cursando el séptimo semestre de nueve que existen.
user_title: Ingeniero En Sistemas Computacionales
email: oleongaytan@gmail.com
# twitter_username: lorem_ipsum
instagram_username: tavo777_
facebook_username: octavio josue leon gaytan
#linkedin_username: murraco
github_username:  OctavioLeonGaytan
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

